# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_show.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(830, 462)
        self.fontComboBox = QtWidgets.QFontComboBox(Form)
        self.fontComboBox.setGeometry(QtCore.QRect(80, 80, 161, 21))
        self.fontComboBox.setStyleSheet("font: 12pt \"Arial\";")
        self.fontComboBox.setObjectName("fontComboBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 80, 51, 24))
        self.label.setStyleSheet("font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 80, 81, 24))
        self.label_2.setStyleSheet("font: 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.char_size_spin = QtWidgets.QSpinBox(Form)
        self.char_size_spin.setGeometry(QtCore.QRect(340, 80, 61, 21))
        self.char_size_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.char_size_spin.setMinimum(1)
        self.char_size_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.char_size_spin.setProperty("value", 12)
        self.char_size_spin.setObjectName("char_size_spin")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 81, 24))
        self.label_3.setStyleSheet("font: 12pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(260, 110, 81, 24))
        self.label_4.setStyleSheet("font: 12pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.py_size_spin = QtWidgets.QSpinBox(Form)
        self.py_size_spin.setGeometry(QtCore.QRect(340, 110, 61, 21))
        self.py_size_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.py_size_spin.setMinimum(1)
        self.py_size_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.py_size_spin.setProperty("value", 12)
        self.py_size_spin.setObjectName("py_size_spin")
        self.char_space_slider = QtWidgets.QSlider(Form)
        self.char_space_slider.setGeometry(QtCore.QRect(110, 200, 221, 22))
        self.char_space_slider.setMaximum(200)
        self.char_space_slider.setProperty("value", 66)
        self.char_space_slider.setOrientation(QtCore.Qt.Horizontal)
        self.char_space_slider.setObjectName("char_space_slider")
        self.char_space_spin = QtWidgets.QSpinBox(Form)
        self.char_space_spin.setGeometry(QtCore.QRect(350, 200, 51, 21))
        self.char_space_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.char_space_spin.setMinimum(0)
        self.char_space_spin.setMaximum(200)
        self.char_space_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.char_space_spin.setProperty("value", 66)
        self.char_space_spin.setObjectName("char_space_spin")
        self.show_set_button = QtWidgets.QPushButton(Form)
        self.show_set_button.setGeometry(QtCore.QRect(640, 420, 71, 31))
        self.show_set_button.setStyleSheet("font: 10pt \"Arial\";")
        self.show_set_button.setObjectName("show_set_button")
        self.check_box = QtWidgets.QCheckBox(Form)
        self.check_box.setGeometry(QtCore.QRect(440, 50, 131, 28))
        self.check_box.setStyleSheet("font: 10pt \"Arial\";")
        self.check_box.setChecked(True)
        self.check_box.setObjectName("check_box")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 340, 81, 24))
        self.label_5.setStyleSheet("font: 12pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 370, 81, 24))
        self.label_6.setStyleSheet("font: 12pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 400, 81, 24))
        self.label_8.setStyleSheet("font: 12pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.char_label_w_slider_2 = QtWidgets.QSlider(Form)
        self.char_label_w_slider_2.setGeometry(QtCore.QRect(110, 340, 221, 22))
        self.char_label_w_slider_2.setMaximum(200)
        self.char_label_w_slider_2.setProperty("value", 50)
        self.char_label_w_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.char_label_w_slider_2.setObjectName("char_label_w_slider_2")
        self.char_label_h_slider = QtWidgets.QSlider(Form)
        self.char_label_h_slider.setGeometry(QtCore.QRect(110, 370, 221, 22))
        self.char_label_h_slider.setMaximum(200)
        self.char_label_h_slider.setProperty("value", 50)
        self.char_label_h_slider.setOrientation(QtCore.Qt.Horizontal)
        self.char_label_h_slider.setObjectName("char_label_h_slider")
        self.py_label_h_slider = QtWidgets.QSlider(Form)
        self.py_label_h_slider.setGeometry(QtCore.QRect(110, 400, 221, 22))
        self.py_label_h_slider.setMaximum(200)
        self.py_label_h_slider.setProperty("value", 50)
        self.py_label_h_slider.setOrientation(QtCore.Qt.Horizontal)
        self.py_label_h_slider.setObjectName("py_label_h_slider")
        self.char_label_w_spin = QtWidgets.QSpinBox(Form)
        self.char_label_w_spin.setGeometry(QtCore.QRect(350, 340, 51, 21))
        self.char_label_w_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.char_label_w_spin.setMinimum(0)
        self.char_label_w_spin.setMaximum(200)
        self.char_label_w_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.char_label_w_spin.setProperty("value", 50)
        self.char_label_w_spin.setObjectName("char_label_w_spin")
        self.char_label_h_spin = QtWidgets.QSpinBox(Form)
        self.char_label_h_spin.setGeometry(QtCore.QRect(350, 370, 51, 21))
        self.char_label_h_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.char_label_h_spin.setMinimum(0)
        self.char_label_h_spin.setMaximum(200)
        self.char_label_h_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.char_label_h_spin.setProperty("value", 50)
        self.char_label_h_spin.setObjectName("char_label_h_spin")
        self.py_label_h_spin = QtWidgets.QSpinBox(Form)
        self.py_label_h_spin.setGeometry(QtCore.QRect(350, 400, 51, 21))
        self.py_label_h_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.py_label_h_spin.setMinimum(0)
        self.py_label_h_spin.setMaximum(200)
        self.py_label_h_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.py_label_h_spin.setProperty("value", 30)
        self.py_label_h_spin.setObjectName("py_label_h_spin")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 108, 24))
        self.label_7.setStyleSheet("font: Bold 14pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 108, 24))
        self.label_9.setStyleSheet("font: Bold 14pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 401, 291))
        self.label_10.setStyleSheet("background-color: rgb(228, 255, 199);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 401, 121))
        self.label_11.setStyleSheet("background-color: rgb(255, 164, 37);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(440, 170, 108, 24))
        self.label_12.setStyleSheet("font: Bold 14pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.win_background_button = QtWidgets.QPushButton(Form)
        self.win_background_button.setGeometry(QtCore.QRect(540, 170, 75, 23))
        self.win_background_button.setObjectName("win_background_button")
        self.msg_background_button = QtWidgets.QPushButton(Form)
        self.msg_background_button.setGeometry(QtCore.QRect(460, 230, 75, 23))
        self.msg_background_button.setObjectName("msg_background_button")
        self.char_color_button = QtWidgets.QPushButton(Form)
        self.char_color_button.setGeometry(QtCore.QRect(590, 230, 75, 23))
        self.char_color_button.setObjectName("char_color_button")
        self.py_color_button = QtWidgets.QPushButton(Form)
        self.py_color_button.setGeometry(QtCore.QRect(710, 230, 75, 23))
        self.py_color_button.setObjectName("py_color_button")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(430, 160, 391, 141))
        self.label_13.setStyleSheet("background-color: rgb(216, 153, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 260, 81, 24))
        self.label_14.setStyleSheet("font: 12pt \"Arial\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20, 230, 81, 24))
        self.label_15.setStyleSheet("font: 12pt \"Arial\";")
        self.label_15.setObjectName("label_15")
        self.msg_space_slider = QtWidgets.QSlider(Form)
        self.msg_space_slider.setGeometry(QtCore.QRect(110, 230, 221, 22))
        self.msg_space_slider.setMaximum(200)
        self.msg_space_slider.setProperty("value", 66)
        self.msg_space_slider.setOrientation(QtCore.Qt.Horizontal)
        self.msg_space_slider.setObjectName("msg_space_slider")
        self.msg_space_spin = QtWidgets.QSpinBox(Form)
        self.msg_space_spin.setGeometry(QtCore.QRect(350, 230, 51, 21))
        self.msg_space_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.msg_space_spin.setMinimum(0)
        self.msg_space_spin.setMaximum(200)
        self.msg_space_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.msg_space_spin.setProperty("value", 66)
        self.msg_space_spin.setObjectName("msg_space_spin")
        self.paragraph_space_slider = QtWidgets.QSlider(Form)
        self.paragraph_space_slider.setGeometry(QtCore.QRect(110, 260, 221, 22))
        self.paragraph_space_slider.setMaximum(200)
        self.paragraph_space_slider.setProperty("value", 66)
        self.paragraph_space_slider.setOrientation(QtCore.Qt.Horizontal)
        self.paragraph_space_slider.setObjectName("paragraph_space_slider")
        self.paragraph_space_spin = QtWidgets.QSpinBox(Form)
        self.paragraph_space_spin.setGeometry(QtCore.QRect(350, 260, 51, 21))
        self.paragraph_space_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.paragraph_space_spin.setMinimum(0)
        self.paragraph_space_spin.setMaximum(200)
        self.paragraph_space_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.paragraph_space_spin.setProperty("value", 66)
        self.paragraph_space_spin.setObjectName("paragraph_space_spin")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(440, 20, 81, 24))
        self.label_16.setStyleSheet("font: Bold 14pt \"微软雅黑\";")
        self.label_16.setObjectName("label_16")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(740, 420, 71, 31))
        self.start_button.setStyleSheet("font: 10pt \"Arial\";")
        self.start_button.setObjectName("start_button")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(440, 70, 101, 24))
        self.label_17.setStyleSheet("font: 12pt \"Arial\";")
        self.label_17.setObjectName("label_17")
        self.win_opacity_spin = QtWidgets.QSpinBox(Form)
        self.win_opacity_spin.setGeometry(QtCore.QRect(760, 70, 51, 21))
        self.win_opacity_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.win_opacity_spin.setMinimum(0)
        self.win_opacity_spin.setMaximum(100)
        self.win_opacity_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.win_opacity_spin.setProperty("value", 0)
        self.win_opacity_spin.setObjectName("win_opacity_spin")
        self.win_opacity_slider = QtWidgets.QSlider(Form)
        self.win_opacity_slider.setGeometry(QtCore.QRect(550, 70, 201, 22))
        self.win_opacity_slider.setMaximum(100)
        self.win_opacity_slider.setProperty("value", 0)
        self.win_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.win_opacity_slider.setObjectName("win_opacity_slider")
        self.obj_opacity_spin = QtWidgets.QSpinBox(Form)
        self.obj_opacity_spin.setGeometry(QtCore.QRect(760, 110, 51, 21))
        self.obj_opacity_spin.setStyleSheet("font: 12pt \"Arial\";")
        self.obj_opacity_spin.setMinimum(0)
        self.obj_opacity_spin.setMaximum(100)
        self.obj_opacity_spin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.obj_opacity_spin.setProperty("value", 0)
        self.obj_opacity_spin.setObjectName("obj_opacity_spin")
        self.obj_opacity_slider = QtWidgets.QSlider(Form)
        self.obj_opacity_slider.setGeometry(QtCore.QRect(550, 110, 201, 22))
        self.obj_opacity_slider.setMaximum(100)
        self.obj_opacity_slider.setProperty("value", 0)
        self.obj_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.obj_opacity_slider.setObjectName("obj_opacity_slider")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(440, 110, 101, 24))
        self.label_18.setStyleSheet("font: 12pt \"Arial\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(530, 30, 151, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(430, 20, 391, 121))
        self.label_20.setStyleSheet("background-color: rgb(255, 164, 37);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.url_edit = QtWidgets.QLineEdit(Form)
        self.url_edit.setGeometry(QtCore.QRect(430, 360, 251, 20))
        self.url_edit.setObjectName("url_edit")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(430, 330, 181, 21))
        self.label_21.setObjectName("label_21")
        self.ok_button = QtWidgets.QPushButton(Form)
        self.ok_button.setGeometry(QtCore.QRect(700, 360, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.label_20.raise_()
        self.label_13.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.fontComboBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.char_size_spin.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.py_size_spin.raise_()
        self.char_space_slider.raise_()
        self.char_space_spin.raise_()
        self.show_set_button.raise_()
        self.check_box.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.char_label_w_slider_2.raise_()
        self.char_label_h_slider.raise_()
        self.py_label_h_slider.raise_()
        self.char_label_w_spin.raise_()
        self.char_label_h_spin.raise_()
        self.py_label_h_spin.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_12.raise_()
        self.win_background_button.raise_()
        self.msg_background_button.raise_()
        self.char_color_button.raise_()
        self.py_color_button.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.msg_space_slider.raise_()
        self.msg_space_spin.raise_()
        self.paragraph_space_slider.raise_()
        self.paragraph_space_spin.raise_()
        self.label_16.raise_()
        self.start_button.raise_()
        self.label_17.raise_()
        self.win_opacity_spin.raise_()
        self.win_opacity_slider.raise_()
        self.obj_opacity_spin.raise_()
        self.obj_opacity_slider.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.url_edit.raise_()
        self.label_21.raise_()
        self.ok_button.raise_()

        self.retranslateUi(Form)
        self.char_space_slider.valueChanged['int'].connect(self.char_space_spin.setValue)
        self.char_space_spin.valueChanged['int'].connect(self.char_space_slider.setValue)
        self.char_label_w_slider_2.valueChanged['int'].connect(self.char_label_w_spin.setValue)
        self.char_label_w_spin.valueChanged['int'].connect(self.char_label_w_slider_2.setValue)
        self.char_label_h_slider.valueChanged['int'].connect(self.char_label_h_spin.setValue)
        self.char_label_h_spin.valueChanged['int'].connect(self.char_label_h_slider.setValue)
        self.py_label_h_slider.valueChanged['int'].connect(self.py_label_h_spin.setValue)
        self.py_label_h_spin.valueChanged['int'].connect(self.py_label_h_slider.setValue)
        self.msg_space_slider.valueChanged['int'].connect(self.msg_space_spin.setValue)
        self.msg_space_spin.valueChanged['int'].connect(self.msg_space_slider.setValue)
        self.paragraph_space_slider.valueChanged['int'].connect(self.paragraph_space_spin.setValue)
        self.paragraph_space_spin.valueChanged['int'].connect(self.paragraph_space_slider.setValue)
        self.win_opacity_slider.valueChanged['int'].connect(self.win_opacity_spin.setValue)
        self.win_opacity_spin.valueChanged['int'].connect(self.win_opacity_slider.setValue)
        self.obj_opacity_slider.valueChanged['int'].connect(self.obj_opacity_spin.setValue)
        self.obj_opacity_spin.valueChanged['int'].connect(self.obj_opacity_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.fontComboBox, self.char_size_spin)
        Form.setTabOrder(self.char_size_spin, self.py_size_spin)
        Form.setTabOrder(self.py_size_spin, self.char_space_slider)
        Form.setTabOrder(self.char_space_slider, self.char_space_spin)
        Form.setTabOrder(self.char_space_spin, self.check_box)
        Form.setTabOrder(self.check_box, self.char_label_w_slider_2)
        Form.setTabOrder(self.char_label_w_slider_2, self.char_label_w_spin)
        Form.setTabOrder(self.char_label_w_spin, self.char_label_h_slider)
        Form.setTabOrder(self.char_label_h_slider, self.char_label_h_spin)
        Form.setTabOrder(self.char_label_h_spin, self.py_label_h_slider)
        Form.setTabOrder(self.py_label_h_slider, self.py_label_h_spin)
        Form.setTabOrder(self.py_label_h_spin, self.show_set_button)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "设置"))
        self.label.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变显示的字体</span></p><p><span style=\" font-size:9pt;\">(包括拼音)</span></p></body></html>"))
        self.label.setText(_translate("Form", "字体："))
        self.label_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变显示的汉字大小</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "汉字字号："))
        self.char_size_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变显示的汉字大小</span></p></body></html>"))
        self.label_3.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">各字符(红框内)之间的横向距离</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "字符间距："))
        self.label_4.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变显示的拼音大小</span></p><p><span style=\" font-size:9pt;\">(一般不比汉字大)</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "拼音字号："))
        self.py_size_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变显示的拼音大小</span></p><p><span style=\" font-size:9pt;\">(一般不比汉字大)</span></p></body></html>"))
        self.char_space_slider.setToolTip(_translate("Form", "<html><head/><body><p>各字符(红框内)之间的横向距离</p></body></html>"))
        self.char_space_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">各字符(红框内)之间的横向距离</span></p></body></html>"))
        self.show_set_button.setText(_translate("Form", "显示预览"))
        self.check_box.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">勾选后窗口会始终保持在其他窗口上方</span></p><p><span style=\" font-size:9pt;\">(游戏全屏时可能不起作用)</span></p></body></html>"))
        self.check_box.setText(_translate("Form", "保持窗口在最上方"))
        self.label_5.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变(红框)宽度</span></p><p><span style=\" font-size:9pt;\">包括拼音的宽度</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "汉字宽度："))
        self.label_6.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变汉字(红框)高度</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "汉字高度："))
        self.label_8.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变拼音(红框)高度</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "拼音高度："))
        self.char_label_w_slider_2.setToolTip(_translate("Form", "<html><head/><body><p>改变(红框)宽度</p><p>包括拼音的宽度</p></body></html>"))
        self.char_label_h_slider.setToolTip(_translate("Form", "<html><head/><body><p>改变汉字(红框)高度</p></body></html>"))
        self.py_label_h_slider.setToolTip(_translate("Form", "<html><head/><body><p>改变拼音(红框)高度</p></body></html>"))
        self.char_label_w_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变(红框)宽度</span></p><p><span style=\" font-size:9pt;\">包括拼音的宽度</span></p></body></html>"))
        self.char_label_h_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变汉字(红框)高度</span></p></body></html>"))
        self.py_label_h_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">改变拼音(红框)高度</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "字体调整"))
        self.label_9.setText(_translate("Form", "字符调整"))
        self.label_12.setText(_translate("Form", "颜色背景"))
        self.win_background_button.setToolTip(_translate("Form", "<html><head/><body><p>这个选项暂时没用哦~</p></body></html>"))
        self.win_background_button.setText(_translate("Form", "窗口背景"))
        self.msg_background_button.setToolTip(_translate("Form", "<html><head/><body><p>每条消息背后的颜色</p></body></html>"))
        self.msg_background_button.setText(_translate("Form", "消息背景"))
        self.char_color_button.setToolTip(_translate("Form", "<html><head/><body><p>要显示的汉字的颜色</p></body></html>"))
        self.char_color_button.setText(_translate("Form", "汉字颜色"))
        self.py_color_button.setToolTip(_translate("Form", "<html><head/><body><p>要显示的拼音的颜色</p></body></html>"))
        self.py_color_button.setText(_translate("Form", "拼音颜色"))
        self.label_14.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">一句话分段(红框间)之间的纵向距离</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "行高："))
        self.label_15.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">各消息之间的纵向距离</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "消息间距："))
        self.msg_space_slider.setToolTip(_translate("Form", "<html><head/><body><p>各消息之间的纵向距离</p></body></html>"))
        self.msg_space_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">各消息之间的纵向距离</span></p></body></html>"))
        self.paragraph_space_slider.setToolTip(_translate("Form", "<html><head/><body><p>一句话分段(红框间)之间的纵向距离</p></body></html>"))
        self.paragraph_space_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">一句话分段(红框间)之间的纵向距离</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "窗口调整"))
        self.start_button.setText(_translate("Form", "开始"))
        self.label_17.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">窗口整体的透明度调整</span></p><p><span style=\" font-size:9pt;\">(数值越高越透明)</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "窗口透明度："))
        self.win_opacity_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">窗口整体的透明度调整</span></p><p><span style=\" font-size:9pt;\">(数值越高越透明)</span></p></body></html>"))
        self.win_opacity_slider.setToolTip(_translate("Form", "<html><head/><body><p>窗口整体的透明度调整</p><p>(数值越高越透明)</p></body></html>"))
        self.obj_opacity_spin.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">这个选项暂时没用哦~</span></p></body></html>"))
        self.obj_opacity_slider.setToolTip(_translate("Form", "<html><head/><body><p>这个选项暂时没用哦~</p></body></html>"))
        self.label_18.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">这个选项暂时没用哦~</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "组件透明度："))
        self.label_19.setText(_translate("Form", "(此类选项重启后生效)"))
        self.label_21.setText(_translate("Form", "直播间地址/房号："))
        self.ok_button.setText(_translate("Form", "确定"))
